apiVersion: apps/v1
kind: Deployment
metadata:
  name: aceest-fitness-app-green
spec:
  replicas: 2
  selector:
    matchLabels:
      app: aceest-fitness-app
      color: green
  template:
    metadata:
      labels:
        app: aceest-fitness-app
        color: green
    spec:
      containers:
      - name: aceest-fitness-container
        image: varunram91/aceest-fitness:initial # Placeholder, will be updated
        ports:
        - containerPort: 8080
